build: false

services:
  - postgresql93

environment:
  global:
    CI_DATABASE: "postgres://postgres:Password12!@127.0.0.1:5432/test_db"
    PGUSER: "postgres"
    PGPASSWORD: "Password12!"

  matrix:
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37-64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\Program Files\\PostgreSQL\\9.3\\bin\\;%PATH%"
  - "python --version"
  - "pip install -r requirements.txt"

before_test:
  - "createdb test_db"

test_script:
  - "python -m unittest"
